### ISSUE TITLE
Issue installing using pip

### ISSUE THREAD

**Issue by pkerpedjiev** [vaexio/vaex#108]
I just tried installing `vaex` and ran into the following error:

```
(cenv3) peter@mbi-cw-l10381:~/projects/higlass-manage [master|!]$ pip install vaex
Collecting vaex
  Using cached https://files.pythonhosted.org/packages/0d/e0/0c495ed2162406832894f93b06ce8d7c1e331ff4b859e5a048417408f3bb/vaex-0.3.10.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/0b/8w70cc7n675fwfd_gsvdvpb00000gp/T/pip-build-xg8b01zh/vaex/setup.py", line 18
        print "Executing: ", cmd
                          ^
    SyntaxError: Missing parentheses in call to 'print'
```
I'm running Python 3.6.1. Installation using conda works up until I try to import it into a Jupyter notebook. See https://github.com/maartenbreddels/vaex/issues/107.

**Comment by maartenbreddels** [comment]
Strange, are you running an old pip maybe?

**Comment by pkerpedjiev** [comment]
I'm not sure. Here's the version:

```
(test_1) pete@twok:~ $ pip --version
pip 9.0.1 from /Users/pete/miniconda3/envs/test_1/lib/python3.6/site-packages (python 3.6)
```

**Comment by jmp75** [comment]
Relating a pip issue as well, I should perhaps open a new issue but this appears to do with changes in pip as well. 

Using Anaconda3 on Linux
```sh
conda activate ELA
cd ~/src/github/
git clone git@github.com:maartenbreddels/vaex.git
cd vaex/
pip install -e .
```
fails with:
```
      File "/xxxx/src/github/vaex/setup.py", line 30, in run
        pip.main(pip_args)
    AttributeError: module 'pip' has no attribute 'main'
```
`pip --version` returns 18.0 . I gather pip jumped from 10 to 18 for some reasons. 

Reading [pip issue 5080](https://github.com/pypa/pip/issues/5080) and related issues sounds like a main() function has been rather abruptly removed since pip 10.x .  Quite a fly on the ointment.
I'll see if I can figure out something and submit a pull request.

**Comment by stevesimmons** [comment]
Under Anaconda 3 in Linux, with Py3.7.1 and pip 18.1 
    pip install vaex
fails with the print error above. 

However
    pip install vaex-arrow
installs `vaex-core` etc and works correctly.

**Comment by maartenbreddels** [comment]
Hi Steve,

try with `vaex install --pre vaex`. That should work fine. I need to go over the docs to see if I missed this somewhere.

cheers,

Maarten

**Comment by pkerpedjiev** [comment]
I guess you meant `pip install --pre vaex`, because that worked :)

**Comment by stestagg** [comment]
Hi.  I'm really struggling to get vaex working using pyenv on OSX.
System versions: Osx 10.14.2,  Xcode: 10.1,  Pyenv: 1.2.8.

============
Python 3.6.4:
```
>  pip install --pre vaex
>  ipython
In [1]: import vaex
ERROR:MainThread:vaex:issue loading ml
Traceback (most recent call last):
  File "/Users/stephenstagg/.pyenv/versions/3.6.4/lib/python3.6/site-packages/vaex/__init__.py", line 548, in <module>
    add_namespace = entry.load()
  File "/Users/stephenstagg/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2343, in load
    return self.resolve()
  File "/Users/stephenstagg/.pyenv/versions/3.6.4/Python.framework/Versions/3.6/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2349, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'vaex.viz'
ERROR:MainThread:vaex:issue loading plot
...
```
I tried pip uninstalling all vaex packages, and re-installing, installing vaex.viz and vaex.astro individually, but still this error


============
Python 3.7.1

First time, kapteyn craps out because numpy isn't installed (ideally it'd be listed as a dependency..)
After installing numpy, trying again gives this at install time:
```
    src/wcs.c:31410:21: error: no member named 'exc_type' in 'struct _ts'
        *type = tstate->exc_type;
                ~~~~~~  ^
```
Full 
[install.log](https://github.com/vaexio/vaex/files/2705182/install.log)

**Comment by maartenbreddels** [comment]
Do you need, vaex-astro? The kapteyn package isn't ported to 3.7 yet, so
you either have to go to 3.6 or so without the astro module. I have to say,
the errors aren't great, I'll see if I can improve on that. Can you give me
the series of commands so I can reproduce?

(from mobile phone)

**Comment by RUrlus** [comment]
@maartenbreddels I ran into the same issue with 3.7 and kapteyn, however, leaving out the astro module still triggered the installation of kapteyn. Switching to 3.6.* works as you mentioned.

Perhaps noting the issue with 3.7 in the, detailed, installation instructions would help.

On a happy note, looking forward to using Vaex

**Comment by maartenbreddels** [comment]
Hi Ralph,

thanks for the report. Did you install skip the 'vaex', for instance, start by only installing `vaex-core` and see if that drags in the kapteyn package. I'll keep this open until resolved.

cheers,

Maarten

**Comment by RUrlus** [comment]
Hi Maarten,

I just tried installing the packages one by one, vaex-ui collects kapteyn through vaex-astro.

`Collecting vaex-astro (from vaex-ui)`
`Collecting kapteyn (from vaex-astro->vaex-ui)`

The others install without issue, so the below works with python 3.7 on MacOS:
`pip install vaex-core vaex-viz vaex-server vaex-hdf5 vaex-distributed`

**Comment by maartenbreddels** [comment]
Great, that is good to hear (and expected). vaex-ui depends on vaex-astro, which depends on kapteyn. This dependency is just removed, but not yet released. I'll ping you when I do, then it should work!

**Comment by athornton** [comment]
FWIW, we here at LSST *would* like Vaex-astro, and our analysis stack has just moved to Python 3.7.

**Comment by maartenbreddels** [comment]
Thanks for letting me know. I guess you'd like to see a release soon?

**Comment by athornton** [comment]
When possible, but it looks like there's no huge hurry...

If you do the find-and-exec bit from https://github.com/SheffieldML/GPy/issues/649, vaex-astro builds.

I'm about to import that into my JupyterLab build environment and see how it goes.

**Comment by athornton** [comment]
The build seems fine, so I have a workaround and there is no hurry.

**Comment by khhyder** [comment]
Using anaconda prompt on Windows OS, following command worked for me:

`conda install -c conda-forge vaex`

You can read the detail instruction here: https://docs.vaex.io/en/latest/installing.html

**Comment by maartenbreddels** [comment]
Note that we don't rely on the kapteyn package anymore. I guess we can close this. Thanks all for the comments.
