### PR TITLE
Feature: adding `dt.floor()` method

### PR DESCRIPTION
**Pull request by JovanVeljanoski**
As suggested by #842, this PR adds  the `.floor()` datetime method.

The usage is as shown in the picture below:
image

### CODE REVIEW

**Comment by maartenbreddels** [comment]
Unrelated failure, seems to have been introduced in https://github.com/vaexio/vaex/pull/826

**Comment by maartenbreddels** [comment]
Looks good!

**Comment by v1gnesh** [comment]
Hi @JovanVeljanoski, when will this make it into the next release please?
Also, when is v4 planned, roughly?

```
{'vaex': '3.0.0',
 'vaex-core': '2.0.3',
 'vaex-viz': '0.4.0',
 'vaex-hdf5': '0.6.0',
 'vaex-server': '0.3.1',
 'vaex-astro': '0.7.0',
 'vaex-jupyter': '0.5.2',
 'vaex-ml': '0.9.0',
 'vaex-arrow': '0.5.1'}
```


```
import vaex
import numpy as np
date = np.array(['2009-10-12T03:31:00', '2016-02-11T10:17:34', '2015-11-12T11:34:22'], dtype=np.datetime64)
df = vaex.from_arrays(date=date)
df.date.dt.floor("H")
```
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-9bbcf48632e7> in <module>
      3 date = np.array(['2009-10-12T03:31:00', '2016-02-11T10:17:34', '2015-11-12T11:34:22'], dtype=np.datetime64)
      4 df = vaex.from_arrays(date=date)
----> 5 df.date.dt.floor("H")

AttributeError: 'DateTime' object has no attribute 'floor'
```

**Comment by JovanVeljanoski** [comment]
Hi, 

If you use pip, you can already install an alpha version of vaex 4, which should include this feature. 
As for a stable v4 release, I am not sure, we are still improving things.
