### ISSUE TITLE
Vaex fails to convert pandas df to vaex df using `from_pandas()`

### ISSUE THREAD

**Issue by voxmenthe** [vaexio/vaex#776]
vaex version: 3.0.0
numpy version: 1.17.3
pandas version: 0.23.4
python version: 3.7.4

Issue: vaex fails to convert a simple pandas dataframe to vaex

# Code example to reproduce:

pandas_df = pd.DataFrame({'x': [0,1,2,3,4], 'y': [0,1,4,9,16]})
vaex_df = vaex.from_pandas(pandas_df)

Fails with: 
AttributeError: module 'pandas.core.arrays' has no attribute 'integer'

Full error message:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-110-9fe4b9718db8> in <module>
      1 #doesn't work in vaex version 3.0.0
----> 2 vaex_df = vaex.from_pandas(pandas_df)

/.venv/lib/python3.7/site-packages/vaex/__init__.py in from_pandas(df, name, copy_index, index_name)
    400                 print("Giving up column %s, error: %r" % (name, e))
    401     for name in df.columns:
--> 402         add(name, df[name])
    403     if copy_index:
    404         add(index_name, df.index)

/.venv/lib/python3.7/site-packages/vaex/__init__.py in add(name, column)
    388     def add(name, column):
    389         values = column.values
--> 390         if isinstance(values, pd.core.arrays.integer.IntegerArray):
    391             values = np.ma.array(values._data, mask=values._mask)
    392         try:

AttributeError: module 'pandas.core.arrays' has no attribute 'integer'

**Comment by JovanVeljanoski** [comment]
Hi, 

I believe this is caused by an issue on the pandas side, which has now been fixed. Can you please update to a more recent version of pandas?

@maartenbreddels we should probably require a more recent pandas version during install of vaex-core?
