### ISSUE TITLE
 AttributeError: 'Hdf5MemoryMapped' object has no attribute '_column_aliases' when reading from S3 

### ISSUE THREAD

**Issue by kaburelabs** [vaexio/vaex#1059]
Hi Fellows, 

I'm trying to read an s3 bucket with the new values version but it's triggering an **attribute error**;

The code snippet that I'm using to it: 
![image](https://user-images.githubusercontent.com/24701735/99276003-f3ccc780-280a-11eb-80de-19e32d3cbe5d.png)

```
INFO:Thread-4:botocore.credentials:Found credentials in shared credentials file: ~/.aws/credentials
ERROR:MainThread:vaex:error opening 's3://amb****ta-r****o-demo-workflows/hdf5/customer_level_table_for_export_2020-08-01.hdf5'
ERROR:MainThread:vaex:error opening 's3://amb****ta-r****o-demo-workflows/hdf5/customer_level_table_for_export_*.hdf5'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<timed exec> in <module>

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, fs_options, *args, **kwargs)
    229                     dfs = []
    230                     for filename in filenames:
--> 231                         dfs.append(vaex.open(filename, convert=bool(convert), shuffle=shuffle, **kwargs))
    232                     df = vaex.concat(dfs)
    233                     if convert:

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/__init__.py in open(path, convert, shuffle, copy_index, fs_options, *args, **kwargs)
    209                         df = from_csv(path, copy_index=copy_index, convert=csv_convert, **kwargs)
    210                     else:
--> 211                         ds = vaex.dataset.open(path, fs_options=fs_options, *args, **kwargs)
    212                         if ds is not None:
    213                             df = vaex.from_dataset(ds)

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/dataset.py in open(path, *args, **kwargs)
     40         if opener.quick_test(path):
     41             if opener.can_open(path, *args, **kwargs):
---> 42                 return opener.open(path, *args, **kwargs)
     43 
     44     # otherwise try all openers

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/dataset.py in open(cls, path, *args, **kwargs)
    914     @classmethod
    915     def open(cls, path, *args, **kwargs):
--> 916         return cls(path, *args, **kwargs)
    917 
    918     def chunk_iterator(self, columns, chunk_size=None, reverse=False):

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/hdf5/dataset.py in __init__(self, path, write, fs_options)
     70         self.h5table_root_name = None
     71         self._version = 1
---> 72         self._load()
     73         if not write:  # in write mode, call freeze yourself, so the hashes are computed
     74             self._freeze()

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/hdf5/dataset.py in _load(self)
    195         if "table" in self.h5file:
    196             self._version = 2
--> 197             self._load_columns(self.h5file["/table"])
    198             self.h5table_root_name = "/table"
    199         root_datasets = [dataset for name, dataset in self.h5file.items() if isinstance(dataset, h5py.Dataset)]

~/anaconda3/envs/test-vaex-test/lib/python3.8/site-packages/vaex/hdf5/dataset.py in _load_columns(self, h5data, first)
    312                     self.ucds[column_name] = ensure_string(column.attrs["ucd"])
    313                 if "alias" in column.attrs:
--> 314                     self._column_aliases[ensure_string(column.attrs["alias"])] = column_name
    315                 if "description" in column.attrs:
    316                     self.descriptions[column_name] = ensure_string(column.attrs["description"])

AttributeError: 'Hdf5MemoryMapped' object has no attribute '_column_aliases'

```

Someone has faced it? It was working perfectly with the same data on the 3.0 version, so I don't know what has changed. 

Also, why it stills reading the credentials and config on ~/.aws even if I set the keys on the fs_option??

My vaex version:
![image](https://user-images.githubusercontent.com/24701735/99288895-03eca300-281b-11eb-9d17-ab9c619ad02e.png)

Thank you very much in advance;
Leonardo

**Comment by maartenbreddels** [comment]
Fixed in https://pypi.org/project/vaex-core/4.0.0a7/ / https://github.com/vaexio/vaex/pull/1071
